### ISSUE TITLE
ERROR: rc from MQTT connect is 4

### ISSUE THREAD

**Issue by nuertey** [coisme/Mbed-to-Google-Cloud-IoT#2]
Hi @coisme ,
Do you know if this sample is still current and works? I followed the detailed instructions but I am getting connection failure. Logs below with sensitive information redacted. Thanks

```
Mbed to Google IoT Cloud: version is 0.10

Opening network interface...
[EasyConnect] IPv4 mode
[EasyConnect] Using Ethernet
[EasyConnect] Connected to Network successfully
...
Network interface opened successfully.

JWT:
...
Connecting to host mqtt.googleapis.com:8883 ...
Connection established.

MQTT client is connecting to the service ...
ERROR: rc from MQTT connect is 4
```

**Comment by nuertey** [comment]
@coisme , FYI, the MQTT Connect error code of 4 apparently refers to :
```
Connection refused: Bad user name or password
```
Since we know that Google Cloud IOT Core does not use the MQTT username, the next most logical question to ask is, are we sure that the Json Web Tokens library is working correctly? Thanks, and I will keep on debugging.
Nuertey

**Comment by coisme** [comment]
Hi @nuertey , sorry that I didn't respond long time... I took a vacation and now having a biz trip.

At least a few month ago, the program worked and connected Google Cloud IoT Core successfully. The JWT library was working at that time. To make JWT correctly, the clock (RTC) on the board should be synced by NTP. I need to check if it still works as is.

**Comment by nuertey** [comment]
Okay, thanks @coisme . Enjoy the vacation and the biz trip. Whenever you are able to get to it is great. I am not in a hurry.

**Comment by nuertey** [comment]
Hi @coisme ,
When you get back, I have put in a pull request for a more robust way of composing the iat and exp on the mbed-jwtgen repository. It does not fix our overall issue but it does resolve the overflows that I am observing in the debug logs. With the fix, the logs are rather like this (I added some more debug traces in my local build) :
```
Mbed to Google IoT Cloud: version is 

Opening network interface...
[EasyConnect] IPv4 mode
[EasyConnect] Using Ethernet
[EasyConnect] Connected to Network successfully
[EasyConnect] MAC address xx:xx:xx:xx:xx:xx
[EasyConnect] IP address xx.xx.xx.xx
Network interface opened successfully.

[DBG ][jwt ]: Nuertey (Time-Based Claim Fields) :-> iat, exp: 0, 1547858057
[DBG ][jwt ]: header: {"alg": "RS256", "typ": "JWT"}
[DBG ][jwt ]: base64(header): eyJhbGciOiAiUlMyNTYiLCAidHlwIjogIkpXVCJ9
[DBG ][jwt ]: Bornyakie (Time-Based Claim Fields) :-> iat, exp: 0, 1547858057
[DBG ][jwt ]: stream: {"aud": "nucleo-f767zi-telemetry", "iat": 1547858057, "exp": 1547861657}
[DBG ][jwt ]: claim: {"aud": "nucleo-f767zi-telemetry", "iat": 1547858057, "exp": 1547861657}
[DBG ][jwt ]: base64(claim): eyJhdWQiOiAibnVjbGVvLWY3Njd6aS10ZWxlbWV0cnkiLCAiaWF0IjogMTU0Nzg1ODA1NywgImV4cCI6IDE1NDc4NjE2NTd9
[DBG ][jwt ]: Base64(sign): ZCpgbYduiWauyvF25B6wyXUvTzzcuziVV1quGlawdQjjgDoA8Wfd4arwR4IseDgCQkSs3wQtBJ7QUOZfxV3ZvJNi3lEHyqjjENU2poUmRUiAUI/dTLIHN8fogtZJYE5q311VKaPT2+w5uUTPyOg+X/0irojwabQEWN9VrkSAU8qHifmiw8bCPvi0TcZvQJXWVnW5nP4eXrTM+DtcnVfucG2rLEXOHqbafYV+qjm49gw2T2OJBP0hh/P3CBeC6y+gEXlMO4Hd8aafsqzFfjh/M7KMx3ySE/Hyw5CC5TB9G2trQBRC84aYqtFgBv/H1lNhtg7Zt3tp7/Z2UtjKEpqdrQ==
JWT:
eyJhbGciOiAiUlMyNTYiLCAidHlwIjogIkpXVCJ9.eyJhdWQiOiAibnVjbGVvLWY3Njd6aS10ZWxlbWV0cnkiLCAiaWF0IjogMTU0Nzg1ODA1NywgImV4cCI6IDE1NDc4NjE2NTd9.ZCpgbYduiWauyvF25B6wyXUvTzzcuziVV1quGlawdQjjgDoA8Wfd4arwR4IseDgCQkSs3wQtBJ7QUOZfxV3ZvJNi3lEHyqjjENU2poUmRUiAUI/dTLIHN8fogtZJYE5q311VKaPT2+w5uUTPyOg+X/0irojwabQEWN9VrkSAU8qHifmiw8bCPvi0TcZvQJXWVnW5nP4eXrTM+DtcnVfucG2rLEXOHqbafYV+qjm49gw2T2OJBP0hh/P3CBeC6y+gEXlMO4Hd8aafsqzFfjh/M7KMx3ySE/Hyw5CC5TB9G2trQBRC84aYqtFgBv/H1lNhtg7Zt3tp7/Z2UtjKEpqdrQ==

Connecting to host mqtt.googleapis.com:8883 ...
[INFO][TLSW]: mbedtls_ssl_config_defaults()
[INFO][TLSW]: mbedtls_ssl_conf_ca_chain()
[INFO][TLSW]: mbedtls_ssl_conf_rng()
[INFO][TLSW]: mbedtls_ssl_conf_authmode()
[INFO][TLSW]: mbedtls_ssl_setup()
[INFO][TLSW]: Starting TLS handshake with mqtt.googleapis.com
[INFO][TLSW]: TLS connection to mqtt.googleapis.com established

[DBG ][TLSW]: Server certificate:
    cert. version     : 3
    serial number     : 12:6B:85:02:2D:B3:92:DE
    issuer name       : C=US, O=Google Trust Services, CN=Google Internet Authority G3
    subject name      : C=US, ST=California, L=Mountain View, O=Google LLC, CN=mqtt.googleapis.com
    issued  on        : 2018-12-19 08:16:00
    expires on        : 2019-03-13 08:16:00
    signed using      : RSA with SHA-256
    RSA key size      : 2048 bits
    basic constraints : CA=false
    subject alt name  : mqtt.googleapis.com, mqtt-mtls.googleapis.com, mqtt-preprod.sandbox.googleapis.com, mqtt-staging.sandbox.googleapis.com, mqtt-test.sandbox.googleapis.com
    ext key usage     : TLS Web Server Authentication


[INFO][TLSW]: Certificate verification passed
Connection established.

MQTT client is connecting to the service ...
[DBG ][TLSW]: send 610
ERROR: rc from MQTT connect is 4
```
Nuertey

**Comment by nuertey** [comment]
Hello @coisme ,
Note that with my current changes in the mbed-jwtgen repo, things seem to work now. At least publishing works. By the way, I had to reduce TIME_JWT_EXP from the maximum to as follows :

```
#define TIME_JWT_EXP      (3600)  // reduce it!
```

Testing logs are as follows :
```
Mbed to Google IoT Cloud: version is 

Opening network interface...
[EasyConnect] IPv4 mode
[EasyConnect] Using Ethernet
[EasyConnect] Connected to Network successfully
[EasyConnect] MAC address xx:xx:xx:xx:xx:xx
[EasyConnect] IP address xx.xx.xx.xx
Network interface opened successfully.

[DBG ][jwt ]: Nuertey (Time-Based Claim Fields) :-> iat, exp: 0, 1548433383
[DBG ][jwt ]: header: {"alg": "RS256", "typ": "JWT"}
[DBG ][jwt ]: base64(header): eyJhbGciOiAiUlMyNTYiLCAidHlwIjogIkpXVCJ9
[DBG ][jwt ]: Bornyakie (Time-Based Claim Fields) :-> iat, exp: 0, 1548433383
[DBG ][jwt ]: stream: {"aud": "nucleo-f767zi-telemetry", "iat": 1548433383, "exp": 1548436983}
[DBG ][jwt ]: claim: {"aud": "nucleo-f767zi-telemetry", "iat": 1548433383, "exp": 1548436983}
[DBG ][jwt ]: base64(claim): eyJhdWQiOiAibnVjbGVvLWY3Njd6aS10ZWxlbWV0cnkiLCAiaWF0IjogMTU0ODQzMzM4MywgImV4cCI6IDE1NDg0MzY5ODN9
[DBG ][jwt ]: Base64(sign): aDNzcJb+vvZIES5M2hgl6Z2eICSH19jBbqrdjEJDhxub8zzrEqaBhHUQhYpmOot8rtipBJ28UzjClbWHz2JApGovAtUS6PaZnqgvyJ1pFG35QYRsT91s3Tnb+GWwEEX0NXX7Sm34TcKWUbMmpG+69XpB5tZIpMFa35XBtphdodPUPJlWslo7/9+SqYMPK3QncDqz0HGbf9PS1q+FUEVjsd/WABZLo9VMLpcEFY+ex06qsRPnRSmJ1y/cKhtij/xfzp+0DoMCQ9jauzj97wUaAK4gzo6OZSGrRXpBbANCYHpf+9+a5BCyylgWNt9i7lapRpJHc9FdAd8U33qjNWBBPg==
JWT:
eyJhbGciOiAiUlMyNTYiLCAidHlwIjogIkpXVCJ9.eyJhdWQiOiAibnVjbGVvLWY3Njd6aS10ZWxlbWV0cnkiLCAiaWF0IjogMTU0ODQzMzM4MywgImV4cCI6IDE1NDg0MzY5ODN9.aDNzcJb+vvZIES5M2hgl6Z2eICSH19jBbqrdjEJDhxub8zzrEqaBhHUQhYpmOot8rtipBJ28UzjClbWHz2JApGovAtUS6PaZnqgvyJ1pFG35QYRsT91s3Tnb+GWwEEX0NXX7Sm34TcKWUbMmpG+69XpB5tZIpMFa35XBtphdodPUPJlWslo7/9+SqYMPK3QncDqz0HGbf9PS1q+FUEVjsd/WABZLo9VMLpcEFY+ex06qsRPnRSmJ1y/cKhtij/xfzp+0DoMCQ9jauzj97wUaAK4gzo6OZSGrRXpBbANCYHpf+9+a5BCyylgWNt9i7lapRpJHc9FdAd8U33qjNWBBPg==

Connecting to host mqtt.googleapis.com:8883 ...
[INFO][TLSW]: mbedtls_ssl_config_defaults()
[INFO][TLSW]: mbedtls_ssl_conf_ca_chain()
[INFO][TLSW]: mbedtls_ssl_conf_rng()
[INFO][TLSW]: mbedtls_ssl_conf_authmode()
[INFO][TLSW]: mbedtls_ssl_setup()
[INFO][TLSW]: Starting TLS handshake with mqtt.googleapis.com
[INFO][TLSW]: TLS connection to mqtt.googleapis.com established

[DBG ][TLSW]: Server certificate:
    cert. version     : 3
    serial number     : 12:6B:85:02:2D:B3:92:DE
    issuer name       : C=US, O=Google Trust Services, CN=Google Internet Authority G3
    subject name      : C=US, ST=California, L=Mountain View, O=Google LLC, CN=mqtt.googleapis.com
    issued  on        : 2018-12-19 08:16:00
    expires on        : 2019-03-13 08:16:00
    signed using      : RSA with SHA-256
    RSA key size      : 2048 bits
    basic constraints : CA=false
    subject alt name  : mqtt.googleapis.com, mqtt-mtls.googleapis.com, mqtt-preprod.sandbox.googleapis.com, mqtt-staging.sandbox.googleapis.com, mqtt-test.sandbox.googleapis.com
    ext key usage     : TLS Web Server Authentication


[INFO][TLSW]: Certificate verification passed
Connection established.

MQTT client is connecting to the service ...
[DBG ][TLSW]: send 622
Client connected.

Client is trying to subscribe a topic "/devices/nuertey-nucleo_f767zi_1/config".
[DBG ][TLSW]: send 46
Client has subscribed a topic "/devices/nuertey-nucleo_f767zi_1/config".

To send a packet, push the button 1 on your board.

Message arrived:


Publishing message to the topic /devices/nuertey-nucleo_f767zi_1/events:
{"cloudRegion":"us-central1","deviceId":"nuertey-nucleo_f767zi_1","registryId":"nuertey_registry","hops":1}
[DBG ][TLSW]: send 151
Message published.
```
I am not sure why the message arrived from IOT Cloud is not working but that is minor and probably depends on IOT Cloud configuration.
Regards
Nuertey

**Comment by nuertey** [comment]
@coisme ,
Once I ensured that the IOT Core configuration has the Runtime set to Node.js 8 (Beta), the Message Arrived also works now. Without that change I was observing the following error on the Cloud Function
```
 resource: {…}  
 severity: "ERROR"  
 textPayload: "TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at exports.relayCloudIot (/user_code/index.js:12:16)
    at /var/tmp/worker/worker.js:761:16
    at /var/tmp/worker/worker.js:709:11
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"  
 timestamp: "2019-01-25T16:23:35.628Z"  
 trace: "projects/nucleo-f767zi-telemetry/traces/d89ba2fbb0d1e1b461adf7c71599a1ad"  
```
So everything works now. Once you merge the Pull Request, we should be good to go.

Nuertey

**Comment by coisme** [comment]
Hi @nuertey ,
I updated mbed-jwtgen revision. I confirmed it worked! :-)

**Comment by nuertey** [comment]
Excellent, @coisme . Thanks. Good to know that it still works :) 

In the future, when I have some time I plan to write and finish a full-blown jwt library for Mbed that supports as many algorithms as it can, example all the variants of RSA, EDSA. PSS, etc. I have already started work on it but I will need sometime before it is mature enough to share. I will publish it as a public repo once it is ready and probably you can help me when time permits with the process of creating a general library for Mbed and some of the testing on other platforms that I do not own. I only own my Nucleo F767ZI for testing.

**Comment by coisme** [comment]
@nuertey That would be great! I'll make the most of your library in my program. I have several Mbed boards. I can help you test it on them.

Let me close this issue.

**Comment by nuertey** [comment]
@coisme ,
I finished the library. It is located at https://github.com/nuertey/jwt-cpp-mbed

The one hurdle remaining is how do I reference my local version of mbed-os in the library. I had to make changes on a local mbed-os branch in order to be able to compile my test cases for Unity/Utest.

```
Workspace/jwt-cpp-mbed/mbed-os$ git branch -a

* jwt-cpp-mbed_unittests

Workspace/jwt-cpp-mbed/mbed-os$ git log
commit 75acb5f2abfc22508ec03f3fb936f204f5fa9af6 (HEAD -> jwt-cpp-mbed_unittests)
Author: Nuertey Odzeyem <nuertey_odzeyem@hotmail.com>
Date:   Fri Feb 15 03:32:34 2019 -0600

    Changelog :
    
    [1] Per similar previous changes in mainline for ARM6, corrected Unity math in GCC_ARM. Unity was failing compilation on GCC_ARM prior to the changes.

```

Let me know what the correct process is to get those changes available to the library. The changes are minor so you can make them manually too if you prefer but they are necessary for compilation to succeed on GCC ARM. Here is a picture of the diff : 
```
-------------- features/frameworks/unity/unity/unity_internals.h --------------
index 337e9f30cc..fe5dbf1221 100644
@@ -41,8 +41,12 @@
 #endif
 
 #ifndef UNITY_EXCLUDE_MATH_H
+#if __cplusplus >= 201103L
+#include <cmath>
+#else
 #include <math.h>
 #endif
+#endif
 
 /*-------------------------------------------------------
  * Guess Widths If Not Specified
@@ -228,6 +232,7 @@ typedef _US64 _U_SINT;
 typedef UNITY_FLOAT_TYPE _UF;
 
 #if defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050)
+#elif defined(__GNUC__)
 #else
 
 #ifndef isinf
@@ -239,7 +244,7 @@ typedef UNITY_FLOAT_TYPE _UF;
 #define isnan(n) ((n != n) ? 1 : 0)
 #endif
 
-#endif /* ARMC6 */
+#endif /* ARMC6 or GCC_ARM*/
 
 #ifndef isneg
 #define isneg(n) ((n < 0.0f) ? 1 : 0)
```

Thanks. And you can create an issue on my library if you prefer us to continue this conversation there as the parent issue here is closed.
Nuertey
